import type { Project } from './types';

import barbereasy from '../../assets/barbereasy-capa.png';
import chamada from '../../assets/chamada.png';
import editor from '../../assets/editor.png';
import apae from '../../assets/apae.png';
import bjtech from '../../assets/bjtech.png';
import alita from '../../assets/alita.png';

// `bjtech` is used as a temporary cover for the Madame e-commerce card, which
// has no dedicated screenshot yet.
export const projects: Project[] = [
  {
    id: 1,
    featured: true,
    badge: 'Featured',
    titleKey: 'project1Title',
    descriptionKey: 'project1Description',
    image: barbereasy,
    imageAlt: 'Interface do BarberEasy',
    technologies: ['PHP', 'Laravel', 'Filament', 'React Native', 'Expo', 'PostgreSQL', 'DigitalOcean'],
    demoUrl: 'https://www.barbereasy.com.br',
    codeUrl: null,
    role: 'Desenvolvedor Full-Stack',
    type: 'SaaS Comercial',
  },
  {
    id: 2,
    featured: false,
    badge: null,
    titleKey: 'project2Title',
    descriptionKey: 'project2Description',
    image: chamada,
    imageAlt: 'Interface da Chamada Digital',
    technologies: ['React', 'TypeScript', 'Firebase'],
    demoUrl: 'https://buja23.github.io/ChamadaDigital-Jiu-view/students',
    codeUrl: 'https://github.com/buja23/ChamadaDigital-Jiu-view',
    role: 'Desenvolvedor Front-End',
    type: 'Sistema Voluntário',
  },
  {
    id: 3,
    featured: false,
    badge: null,
    titleKey: 'project3Title',
    descriptionKey: 'project3Description',
    image: bjtech,
    imageAlt: 'Interface do E-commerce Madame',
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe', 'Tailwind'],
    demoUrl: null,
    codeUrl: null,
    role: 'Desenvolvedor Full-Stack',
    type: 'Plataforma Varejo',
  },
  {
    id: 4,
    featured: false,
    badge: null,
    titleKey: 'project4Title',
    descriptionKey: 'project4Description',
    image: editor,
    imageAlt: 'Interface do editor de vídeo',
    technologies: ['Vue', 'Electron', 'FFmpeg', 'Figma'],
    demoUrl: null,
    codeUrl: null,
    role: 'Desenvolvedor Full-Stack',
    type: 'Editor de Vídeo',
  },
  {
    id: 5,
    featured: false,
    badge: null,
    titleKey: 'project5Title',
    descriptionKey: 'project5Description',
    image: apae,
    imageAlt: 'Interface do controle de estoque da APAE',
    technologies: ['PHP', 'MySQL'],
    demoUrl: null,
    codeUrl: 'https://github.com/JoaoPCisilo/APAE',
    role: 'Desenvolvedor Full-Stack',
    type: 'Projeto Social',
  },
  {
    id: 6,
    featured: false,
    badge: null,
    titleKey: 'project6Title',
    descriptionKey: 'project6Description',
    image: bjtech,
    imageAlt: 'Interface do sistema de controle de vendas',
    technologies: ['React', 'Node.js', 'MongoDB'],
    demoUrl: null,
    codeUrl: 'https://github.com/buja23/BG-BJ-tec',
    role: 'Desenvolvedor Full-Stack',
    type: 'Sistema de Gestão',
  },
  {
    id: 7,
    featured: false,
    badge: null,
    titleKey: 'project7Title',
    descriptionKey: 'project7Description',
    image: alita,
    imageAlt: 'Cena do jogo 2D Alita',
    technologies: ['GameMaker 2', 'GML', 'Piskel'],
    demoUrl: null,
    codeUrl: null,
    role: 'Desenvolvedor de Jogos',
    type: 'Jogo 2D',
  },
];
